service: lambda

plugins:
  - serverless-esbuild
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1

functions:
  hello:
    handler: src/functions/hello.handle
    events:
      - httpApi: 'GET /hello'
