service: certification
useDotenv: true

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-dynamodb-local
  - serverless-iam-roles-per-function
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x
  region: ${env:AWS_PROVIDER_REGION}
  lambdaHashingVersion: 20200924
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

custom: 
  dynamodb:
    stages:
      - dev
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true
      

functions:
  generateCertificate:
    handler: src/functions/generateCertificate.handle
    events:
      - httpApi: 'POST /certificate'
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
          - dynamodb:PutItem
        Resource: "arn:aws:dynamodb:${env:AWS_PROVIDER_REGION}:*:table/${env:AWS_DYNAMODB_TABLE_NAME}"
  verifyCertificate:
    handler: src/functions/verifyCertificate.handle
    events:
      - httpApi: 'GET /certificate/{id}'
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: "arn:aws:dynamodb:${env:AWS_PROVIDER_REGION}:*:table/${env:AWS_DYNAMODB_TABLE_NAME}"

resources:
  Resources:
    dbCertificateUsers: 
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:AWS_DYNAMODB_TABLE_NAME}
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema: 
          - AttributeName: id
            KeyType: HASH

package:
    include:
      - src/views

